version: '2'
services:
  cloudkeeper:
    image: cloudkeeper
    volumes:
      - /etc/grid-security/hostcert.pem:/etc/grid-security/hostcert.pem
      - /etc/grid-security/hostkey.pem:/etc/grid-security/hostkey.pem
      - /etc/grid-security/certificates/:/etc/grid-security/certificates/
    ports:
      - "50505:50505"
  cloudkeeper-os:
    image: cloudkeeper-os
    volumes:
    links:
      - cloudkeeper
