version: "2"
services:
  cloudkeeper:
    image: cloudkeeper:latest
    volumes:
      - /etc/grid-security:/etc/grid-security
    links:
      - cloudkeeper-os
  cloudkeeper-os:
    image: cloudkeeper-os:latest
    volumes:
      - /etc/grid-security:/etc/grid-security
    expose:
      - "50505"

