FROM centos:7
MAINTAINER Luís Alves <lalves@lip.pt>

RUN yum -y update
RUN yum install -y https://repos.fedorapeople.org/repos/openstack/openstack-mitaka/rdo-release-mitaka-7.noarch.rpm
RUN yum install -y curl epel-release python-glanceclient python-keystoneauth1 python-oslo-config python-oslo-log supervisor \
        http://grand-est.fr/resources/software/cloudkeeper-os/centos/7/x86_64/python-grpcio-1.3.5-1.el7.centos.x86_64.rpm \
        http://grand-est.fr/resources/software/cloudkeeper-os/centos/7/x86_64/protobuf-3.3.0-1.el7.centos.x86_64.rpm \
        http://grand-est.fr/resources/software/cloudkeeper-os/centos/7/x86_64/cloudkeeper-os-0.8.0-2.el7.centos.x86_64.rpm \
        http://grand-est.fr/resources/software/cloudkeeper-os/centos/7/noarch/python2-protobuf-3.3.0-1.el7.centos.noarch.rpm
RUN yum clean all

RUN mkdir etc/cloudkeeper-os \
    && curl -L https://raw.githubusercontent.com/the-cloudkeeper-project/cloudkeeper-os/master/etc/cloudkeeper-os/cloudkeeper-os-config-generator.conf > etc/cloudkeeper-os/cloudkeeper-os-config-generator.conf \
    && oslo-config-generator --config-file etc/cloudkeeper-os/cloudkeeper-os-config-generator.conf --output etc/cloudkeeper-os/cloudkeeper-os.conf

RUN systemctl enable cloudkeeper-os.service

EXPOSE 50505

CMD ["/usr/sbin/init"]
