FROM centos:7
MAINTAINER Luís Alves <lalves@lip.pt>

RUN yum -y update
RUN yum install -y --nogpgcheck https://repos.fedorapeople.org/repos/openstack/openstack-mitaka/rdo-release-mitaka-7.noarch.rpm epel-release
RUN yum install -y --nogpgcheck wget nginx python2-glanceclient python-keystoneauth1 python-oslo-config python-oslo-log \
        http://repository.egi.eu/sw/untested/cmd-os/1/centos7/x86_64/cloudkeeper-1.5.0+20170710170557-1.el7.x86_64.rpm

COPY cloudkeeper.yml etc/cloudkeeper/cloudkeeper.yml

RUN wget -P etc/cron.d/ https://raw.githubusercontent.com/the-cloudkeeper-project/cloudkeeper/master/examples/etc/cron.d/cloudkeeper

CMD ["/usr/bin/cloudkeeper"]
